/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Otherpunks } from "./Otherpunks";

export { Otherpunks__factory } from "./factories/Otherpunks__factory";
