/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Mineablepunks } from "./Mineablepunks";

export { Mineablepunks__factory } from "./factories/Mineablepunks__factory";
